// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/rates": {
            "get": {
                "description": "Возвращает курсы валют на основе переданных параметров",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Курсы валют"
                ],
                "summary": "Получить курсы валют",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Список валют через запятую",
                        "name": "currencies",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Возвращает список курсов валют\" // Указываем полный путь до типа Rate",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Rate"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Rate": {
            "type": "object",
            "properties": {
                "current_price": {
                    "type": "number"
                },
                "high_24h": {
                    "type": "number"
                },
                "last_updated": {
                    "type": "string"
                },
                "low_24h": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "price_change_percentage_1h_in_currency": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Currency API",
	Description:      "API для получения курсов валют",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
